# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: devmaster

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job
  - job: SecondJob
    steps:
    - bash: echo Build First Job
- stage: DevDeploy
  jobs:
  - job: Dev Deploy Job
    steps:
    - bash: echo Build Dev Deploy Job
- stage: QADeploy
  jobs:
  - job: QA Deploy Job
    steps:
    - bash: echo Build QA Deploy Job
- stage: ProdDeploy
  jobs:
  - job: Prod Deploy Job
    steps:
    - bash: echo Build Prod Deploy Job
