# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: devmaster

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First Job
  - job: SecondJob
    steps:
    - bash: echo Build First Job
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo Build Dev Deploy Job
- stage: QADeploy
  dependsOn: DevDeploy
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo Build QA Deploy Job
- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployJob
    steps:
    - bash: echo Build Prod Deploy Job
