trigger:
- master

# strategy:
#   matrix:
#     linux:
#       operatingSystem: 'devmaster'
#     mac:
#       operatingSystem: 'devmaster'

pool: devmaster

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Do the build"
- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo deploy to Dev
- stage: QADeploy
  jobs:
  - deployment: DevDeployJob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo deploy to Dev